---
".gitlab-ci.yml":
  delete: true
".travis.yml":
  dist: xenial
  deploy_to_forge:
    enabled: false
  branches:
  - release
  use_litmus: true
  litmus:
    provision_list:
    - ---travis_el
    - travis_deb
    - travis_el7
    - travis_el8
    complex:
    - collection:
        puppet_collection:
        - puppet6
        provision_list:
        - travis_ub_6
    - collection:
        puppet_collection:
        - puppet5
        provision_list:
        - travis_ub_5
  simplecov: true
  notifications:
    slack:
      secure: XCjKJZ+9tX+z0ONd9h5H4jrwxU1V6WbcrZYfRB66KJEDH+Zxa6sJvU2SHoH3H4yAn5DNhAi/syzWJl4Ht/23CAR4qr0GmdDZxr8xUaha2jmB3nrletTqzftxMgNJUvZ3ZpsSmPpBS+9jQKZ6IoXrVJI+Y9mzXd7oGeFENPiHk3o=
appveyor.yml:
  delete: true
Gemfile:
  optional:
    ":development":
    - gem: github_changelog_generator
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
.gitpod.Dockerfile:
  unmanaged: false
.gitpod.yml:
  unmanaged: false
.github/workflows/nightly.yml:
  unmanaged: false
.github/workflows/pr_test.yml:
  unmanaged: false
