---
".gitlab-ci.yml":
  delete: true
".travis.yml":
  dist: xenial
  deploy_to_forge:
    enabled: false
  branches:
  - release
  use_litmus: true
  litmus:
    provision_list:
      - travis_ub
      - travis_deb
      - travis_el6
      - travis_el7
  simplecov: true
  notifications:
    slack:
      secure: XCjKJZ+9tX+z0ONd9h5H4jrwxU1V6WbcrZYfRB66KJEDH+Zxa6sJvU2SHoH3H4yAn5DNhAi/syzWJl4Ht/23CAR4qr0GmdDZxr8xUaha2jmB3nrletTqzftxMgNJUvZ3ZpsSmPpBS+9jQKZ6IoXrVJI+Y9mzXd7oGeFENPiHk3o=
appveyor.yml:
  delete: true
Gemfile:
  optional:
    ":development":
    - gem: github_changelog_generator
      git: https://github.com/skywinder/github-changelog-generator
      ref: 20ee04ba1234e9e83eb2ffb5056e23d641c7a018
      condition: Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
